Refactor.  Don't log to the tab while reading from the tab.

diff --git a/bin/tally b/bin/tally
--- a/bin/tally
+++ b/bin/tally
@@ -6,21 +6,27 @@
 # Version 2, as published by Sam Hocevar. See WTFPL.txt or
 # http://www.wtfpl.net/ for more details.
 
-source utilities.sh
-source function_tally.sh
-source function_new_food.sh
-source function_interactive.sh
+main_dir="$(readlink -f "${0%/*}/..")" \
+  || fail "Failed to get absolute path of main directory."
+lib_dir="${main_dir}/lib"
 
-FOOD="x"
-TALLY="0"
-DATE="$(date "+%Y%m%d")"
-TAB="state/days/${DATE}"
+libs=(
+  "config"
+  "io"
+  "tally"
+  "new_food"
+  "serving_points"
+)
+
+for lib in "${libs[@]}"; do
+  source "${lib_dir}/${lib}"
+done
 
 if [ -f "${TAB}" ]
 then
   output "You have a tab for ${DATE}.  [c]ontinue or [o]verwrite? [C,o]  "
   read REPLY
-  if echo "${REPLY}" | grep -i "^o"
+  if echo "${REPLY}" | grep -qi "^o"
   then
     output "Overwriting your old tab.\n"
     > "${TAB}"
