Allow overwriting weight.

diff --git a/bin/weigh-in b/bin/weigh-in
--- a/bin/weigh-in
+++ b/bin/weigh-in
@@ -24,5 +24,17 @@ for lib in "${libs[@]}"; do
 done
 
 sync_state
+if test -f "${weigh_in}"; then
+  weight="$(distill "$(< "${weigh_in}")")" \
+    || fail "Failed to read weight."
+  output "Weight:" "${weight}"
+  prompt "Overwrite?  [y,N]"
+  read response
+  if ! grep -qi 'y' <<< "${response}"; then
+    exit 0
+  fi
+  rm "${weigh_in}" \
+    || fail "Failed to remove old weight file."
+fi
 weigh_in
 sync_state
