Move toward combined analysis of days.

diff --git a/lib/analyze b/lib/analyze
--- a/lib/analyze
+++ b/lib/analyze
@@ -8,41 +8,60 @@
 
 
 function analyze() {
-	foods=()
-	days=()
-	points_by_day=()
-	points_by_food=()
-	points_total=0
+  foods=()
+  days=()
+  points_by_day=()
+  points_by_food=()
+  points_total=0
   d=0
   while read day; do
-		days["${d}"]="${day}"
+    days["${d}"]="${day}"
 #    output "Day:" "${day}"
     set -o pipefail
-    analyze_day < "${state}/days/${day}" \
-      | while read food; do
-        read servings
-        read points
-				points_by_day["${d}"]="$(calculate "${points_by_day["${d}"]} + ${points}")"
-				f=0
-				for compiled_food in "${foods[@]}"; do
-					if test "${compiled_food}" = "${food}"; then
-						break 1
-					fi
-					f="$(( f + 1 ))"
-				done
-				if test "${#foods[@]}" = "${f}"; then
-					foods["${f}"]="${food}"
-				fi
-				points_by_food["${d}"]="$(calculate "${points_by_food["${d}"]} + ${points}")"
+    while read food; do
+      read servings
+      read points
+      if ! grep -qE '^[-0-9.]+$' <<< "${servings}"; then
+        fail "Invalid number of servings of '${food}':" "'${servings}'"
+      fi
+      if ! grep -qE '^[-0-9.]+$' <<< "${points}"; then
+        fail "Invalid number of points for '${food}':" "'${points}'"
+      fi
+      points_by_day["${d}"]="$(
+        calculate "${points_by_day["${d}"]:-0} + ${points}"
+      )" || fail "Failed to calculate points by day."
+      points_total="$(
+        calculate "${points_total} + ${points}"
+      )" || fail "Failed to calculate points total."
+      f=0
+      for compiled_food in "${foods[@]}"; do
+        if test "${compiled_food}" = "${food}"; then
+          break 1
+        fi
+        f="$(( f + 1 ))"
+      done
+      if test "${#foods[@]}" = "${f}"; then
+        foods["${f}"]="${food}"
+      fi
+      points_by_food["${d}"]="$(
+        calculate "${points_by_food["${d}"]:-0} + ${points}"
+      )" || fail "Failed to calculate points by food."
 #        output "Food:" "${food}"
 #        output "Servings:" "${servings}"
 #        output "Points:" "${points}"
-      done \
-      || fail "Failed to analyze day:" "${day}"
+    done < <(
+      ( analyze_day < "${state}/days/${day}" ) \
+        || printf 'x\nx\nx\n'  # Cheap hack to induce parse failure.
+    ) || fail "Failed to analyze day:" "${day}"
     set +o pipefail
 #    output
     d="$(( d + 1 ))"
   done < <(ls "${state}/days/" | sort)
+  average_points="$(
+    calculate "${points_total} / ${#days[@]}"
+  )" || fail "Failed to calculate average points."
+  output "Number of days:" "${#days[@]}"
+  output "Average points per day:" "${average_points}"
 }
 
 
