Incorporate executor suite.

diff --git a/lib/tally_then_tally b/lib/tally_then_tally
--- a/lib/tally_then_tally
+++ b/lib/tally_then_tally
@@ -6,12 +6,17 @@
 # Version 2, as published by Sam Hocevar. See WTFPL.txt or
 # http://www.wtfpl.net/ for more details.
 
-prefix="${name}:  "
-if test 6 -gt "$(date '+%H')"; then
-  date="$(date "+%Y%m%d" -d '-1day')"
-else
-  date="$(date "+%Y%m%d")"
-fi
-state="${local_lib}/../state"
-log="${state}/days/${date}"
-weigh_in="${state}/weights/${date}"
+include real_tally
+include config
+include fail
+
+
+# Tally up the log, then take new input from the user.
+function tally_then_tally() {
+    tally=0
+    if [ -f "${log}" ]; then
+      tally="$(NONINTERACTIVE='y' real_tally < "${log}")" \
+        || fail "Failed to tally existing tab."
+    fi
+    real_tally
+}
